# -*- coding: utf-8 -*-
"""day4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bd_Xa4WjUz0R31cFCUGB7NFuHr0987LO
"""

#task1 :circle calculator
pi=3.14159
def circle_calculator(r):
  print(f"Circle area:{pi*r*r}")
  print(f"Circle circumference:{2*pi*r}")
r=(float(input("Enter the Radius:")))
circle_calculator(r)



#task 2:Palindrome Checker
text=input("enter the Text:").lower()
if text==text[::-1]:
  print("Palindrome")
else:
  print("Non Palindrome")

#task 2:Palindrome Checker
text=input("enter the Text:").lower()
if text==text[::-1]:
  print("Palindrome")
else:
  print("Non Palindrome")

#task3 Password Genereator
import string
import random

def genrate_password(length=12):
  characters = string.ascii_letters + string.digits + string.punctuation
  password = ""
  for _ in range(length):
    password += random.choice(characters)
  return password

password_length = int(input("Enter the desired password length: "))
password = genrate_password(password_length)
print("Generated Password:", password)
for i in range(5):
 print(f"passward No.{i+1}={genrate_password()} \n")

#task4 sentence analyser
text=input("Enter the Text:")
vowels=['a','e','i','o','u']
def analyse_sentence(text):
   word_count=0
   vowel_count=0
   cons_count=0
   largest=''
   shortest=''
   for ch in text.split():
    if ch.isalpha():
      word_count+=1
   for ch in list(text.lower()):
    if ch in vowels:
      vowel_count+=1
    else:
      cons_count+=1
    words=text.split()
    largest=words[0]
    shortest=words[0]
    for ch in words:
      if len(ch)>len(largest):
        largest=ch
      if len(ch)<len(shortest):
        shortest=ch
    analyse={
    'word_count':word_count,
    'vowel_count':vowel_count,
    'cons_count':cons_count,
    'largest':largest,
    'shortest':shortest
    }
   print(analyse)
analyse_sentence(text)

#Task5 converter Toolkit
def km_to_miles(km):
    miles = km * 0.621371
    print(f"{km} km = {miles:.2f} miles")

def kg_to_pounds(kg):
    lbs = kg * 2.20462
    print(f"{kg} kg = {lbs:.2f} pounds")

def litres_to_gallons(l):
    gall = l * 0.264172
    print(f"{l} litres = {gall:.2f} gallons")

# main loop
while True:
    k = int(input("Do you want to continue?\n1. Continue\n2. Quit\n"))
    if k == 2:
        print("Exiting converter toolkit...")
        break

    print("Choose the conversion:\n 1. km to Miles \n 2. kg to Pounds \n 3. Litres to Gallons\n")
    m = int(input("Enter your choice: "))

    if m == 1:
        km = float(input("Enter km: "))
        km_to_miles(km)
    elif m == 2:
        kg = float(input("Enter kg: "))
        kg_to_pounds(kg)
    elif m == 3:
        l = float(input("Enter litres: "))
        litres_to_gallons(l)
    else:
        print("Invalid choice, try again.")

def get_student_info():
    name = input("Enter the name: ")
    marks = []
    for i in range(5):
        marks.append(int(input(f"Enter the marks for subject {i+1}: ")))
    return name, marks

def calculate_stats(marks):
    total = sum(marks)
    avg = total / len(marks)
    highest = max(marks)
    lowest = min(marks)
    return {
        "Total": total,
        "Average": avg,
        "Highest": highest,
        "Lowest": lowest
    }

def determine_grade(avg):
    if avg >= 90:
        return "A"
    elif avg >= 80:
        return "B"
    elif avg >= 70:
        return "C"
    elif avg >= 60:
        return "D"
    else:
        return "F"

# Main program
name, marks = get_student_info()
stats = calculate_stats(marks)
grade = determine_grade(stats["Average"])

print("\n--- Report Card ---")
print(f"Name: {name}")
print(f"Marks: {marks}")
print(f"Total: {stats['Total']}")
print(f"Average: {stats['Average']:.2f}")
print(f"Highest Marks: {stats['Highest']}")
print(f"Lowest Marks: {stats['Lowest']}")
print(f"Grade: {grade}")